# Generated by Django 5.0.1 on 2024-02-09 15:37

import server.models
import server.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0003_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="server_banners",
                validators=[
                    server.validators.validate_banner_image,
                    server.validators.validate_image_file_extensions,
                ],
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="server_icons",
                validators=[
                    server.validators.validate_icon_image,
                    server.validators.validate_image_file_extensions,
                ],
            ),
        ),
    ]
